export const kecamatanWithDesaKelurahan = {
  //komplit anjir.
  Lobalain: [
    'Desa Sanggaoen',
    'Desa Kolobolon',
    'Desa Bebalain',
    'Desa Suelain',
    'Desa Kuli',
    'Desa Helebeik',
    'Desa Oematamboli',
    'Desa Baadale',
    'Desa Holoama',
    'Desa Tuanatuk',
    'Desa Oelunggu',
    'Desa Oeleka',
    'Desa Lekunik',
    'Desa Loleoen',
    'Desa Kuli Aisele',
  ],
  //komplit anjir.
  'Rote Tengah': [
    'Desa Suebela',
    'Desa Nggodimeda',
    'Desa Maubesi',
    'Desa Lidabesi',
    'Desa Lidamanu',
    'Desa Limakoli',
    'Desa Siomeda',
  ],
  //komplit anjir.
  'Pantai Baru': [
    'Desa Oeledo',
    'Desa Sonimanu',
    'Desa Oebau',
    'Desa Nusakdale',
    'Desa Keoen',
    'Desa Edalode',
    'Desa Tesabela',
    'Desa Tungganamo',
    'Desa Batulilok',
    'Desa Lenupetu',
    'Desa Fatelilo',
    'Desa Ofalangga',
    'Desa Oenggae',
    'Desa Lekona',
  ],

  //komplit anjir.
  'Rote Timur': [
    'Desa Serubeba',
    'Desa Lakamola',
    'Desa Mukekuku',
    'Desa Faifua',
    'Desa Hundihopo',
    'Desa Matasio',
    'Desa Penggodua',
    'Desa Batefalu',
    'Desa Papela',
    'Desa Matanae',
  ],
  //komplit anjir.
  'Landu Leko': [
    'Desa Bolatena',
    'Desa Sotimori',
    'Desa Daiama',
    'Desa Pukuafu',
    'Desa Daurendale',
    'Desa Lifule',
    'Desa Tenalai',
  ],
  ' Ndao Nuse': ['Desa Nuse', 'Desa Anarae', 'Desa Mbiu Lombo', 'Desa Lendeiki', 'Desa Ndao Nuse'],

  'Rote Barat Laut': [
    'Desa Oebela',
    'Desa Boni',
    'Desa Tolama',
    'Desa Oelua',
    'Desa Netenaen',
    'Desa Oetutulu',
    'Desa Daudolu',
    'Desa Modosinal',
    'Desa Ingguinak',
    'Desa Temas',
    'Desa Lidor',
    'Desa Tualima',
    'Desa Balaoli',
    'Desa Tasilo',
    'Desa Oebole',
    'Desa Hululai',
    'Desa Hundihuk',
    'Desa Saindale',
    'Desa Mundek',
    'Desa Busalangga Barat',
    'Desa Busalangga Timur',
  ],

  'Rote Barat Daya': [
    'Desa Oetefu',
    'Desa Oeseli',
    'Desa Oebou',
    'Desa Oehandi',
    'Desa Lalukoen',
    'Desa Meoain',
    'Desa Oebafok',
    'Desa Oebatu',
    'Desa Batutua',
    'Desa Lekik',
    'Desa Mbokak',
    'Desa Dolasi',
    'Desa Oelasin',
    'Desa Landu',
    'Desa Lentera',
    'Desa Sakubatun',
    'Desa Dalekesa',
    'Desa Sanggandolu',
    'Desa Fuafuni',
  ],

  'Rote Barat': [
    'Desa Oenitas',
    'Desa Oelolot',
    'Desa Mbueain',
    'Desa Sedeoen',
    'Desa Nemberala',
    'Desa Bo’a',
    'Desa Oenggaut',
  ],

  'Rote Selatan': [
    'Desa Tebole',
    'Desa Dodaek',
    'Desa Inaoe',
    'Desa Daleholu',
    'Desa Lengguselu',
    'Desa Nggelodae',
    'Desa Pilasue',
  ],

  Loaholu: ['Balaoli', 'Boni', 'Holulai', 'Lidor', 'Mundek', 'Obelob', 'Oelua', 'Tasilu', 'Tolama'],


  //   'Ndao Nuse': ['Anaræ', 'Mbali Lendeiki', 'Mbiu Lombo', 'Ndao Nuse', 'Nuse'],
  //   'Landu Leko': ['Bolatena', 'Dauerendale', 'Daiama', 'Lifuleo', 'Pukufai', 'Sotimori', 'Tena Lai'],
}
